/**
 * Bundle a project's cached source package into the standalone web build.
 *
 * The browser app normally reads the cached page and assets from the Vite dev
 * server's view of `fixtures/`. A hosted build has no dev server and no access
 * to the developer's machine, so the source package has to travel with it.
 *
 * Two channels, chosen for what a restrictive host will actually allow:
 *
 *  - the page HTML is **inlined** into the bundle as a string, so no request is
 *    needed to read it;
 *  - the images are emitted as ordinary files next to the bundle and loaded
 *    through `<img>`, which is a plain image load rather than a scripted fetch.
 *
 * Nothing is resampled or re-encoded: the bytes written here are the bytes the
 * Node fetch cache stored, so the hosted build analyses exactly what the CLI
 * analysed.
 */
import { mkdir, readFile, readdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { parseArchonPage } from '../src/core/source/archon-parser.js'
import { sha256 } from '../src/core/util/hash.js'
import { projectByKey, PROJECTS } from '../src/node/projects.js'

const OUT_ASSETS = 'dist-standalone-src/assets'
const OUT_TS = 'src/web/bundled/index.ts'

/** Magic-byte sniff: the fetch cache stores everything as `.bin`. */
const mediaTypeOf = (bytes: Buffer): { type: string; ext: string } => {
  if (bytes[0] === 0xff && bytes[1] === 0xd8) return { type: 'image/jpeg', ext: 'jpg' }
  if (bytes[0] === 0x89 && bytes[1] === 0x50) return { type: 'image/png', ext: 'png' }
  if (bytes[0] === 0x47 && bytes[1] === 0x49) return { type: 'image/gif', ext: 'gif' }
  return { type: 'application/octet-stream', ext: 'bin' }
}

const keys = process.argv.slice(2)
const wanted = (keys.length > 0 ? keys : ['A']).map((k) => {
  const p = projectByKey(k)
  if (!p) throw new Error(`unknown project ${k}; known: ${PROJECTS.map((x) => x.key).join(', ')}`)
  return p
})

await rm('dist-standalone-src', { recursive: true, force: true })
await mkdir(OUT_ASSETS, { recursive: true })
await mkdir('src/web/bundled', { recursive: true })

type BundledProject = {
  key: string
  name: string
  url: string
  projectCode: string
  html: string
  /** Published file name per asset URL basename. */
  assets: Array<{ basename: string; file: string; type: string; bytes: number }>
}

const bundled: BundledProject[] = []

for (const project of wanted) {
  const html = await readFile(`fixtures/${project.slug}/page.html`, 'utf8')
  const pkg = parseArchonPage(html, project.url)
  // The cache is keyed by URL hash, so match cached files to assets by
  // decoding each and comparing sizes is unnecessary: the loader below matches
  // by *basename*, exactly as the dev-server path does, so the published name
  // must be the asset URL's own basename.
  const cacheDir = `fixtures/${project.slug}/assets`
  const cached = await readdir(cacheDir)
  const byHash = new Map<string, string>()
  for (const f of cached) byHash.set(f, join(cacheDir, f))

  // Re-derive the cache key the Node adapter uses: the portable SHA-256 of the
  // URL, truncated. Using the core implementation rather than node:crypto keeps
  // the two in step by construction.
  const cacheKey = (url: string): string => sha256(new TextEncoder().encode(url)).slice(0, 24)

  const assets: BundledProject['assets'] = []
  for (const asset of pkg.assets) {
    const key = cacheKey(asset.url)
    const path = byHash.get(`${key}.bin`)
    if (!path) {
      console.warn(`  ! no cached bytes for ${asset.role} (${asset.url.slice(-40)}) — run "npm run fetch ${project.key} -- --online"`)
      continue
    }
    const bytes = await readFile(path)
    const { type, ext } = mediaTypeOf(bytes)
    const basename = asset.url.slice(asset.url.lastIndexOf('/') + 1)
    const file = `${key}.${ext}`
    await writeFile(join(OUT_ASSETS, file), bytes)
    assets.push({ basename, file, type, bytes: bytes.length })
  }
  bundled.push({
    key: project.key,
    name: project.name,
    url: project.url,
    projectCode: project.url.slice(project.url.lastIndexOf('-') + 1),
    html,
    assets,
  })
  const total = assets.reduce((a, x) => a + x.bytes, 0)
  console.log(`${project.key} ${project.name}: ${assets.length}/${pkg.assets.length} assets, ${(total / 1e6).toFixed(2)} MB, page ${(html.length / 1e3).toFixed(0)} kB`)
}

const literal = (s: string): string => JSON.stringify(s)

const source = `/**
 * GENERATED by scripts/build-standalone.ts — do not edit.
 *
 * The cached source packages that travel with the standalone web build. The
 * page HTML is inlined; the images sit beside the bundle and are named by the
 * same cache key the Node adapter uses.
 */
export type BundledAsset = { basename: string; file: string; type: string; bytes: number }

export type BundledProject = {
  key: string
  name: string
  url: string
  projectCode: string
  html: string
  assets: BundledAsset[]
}

export const BUNDLED_PROJECTS: BundledProject[] = [
${bundled
  .map(
    (p) => `  {
    key: ${literal(p.key)},
    name: ${literal(p.name)},
    url: ${literal(p.url)},
    projectCode: ${literal(p.projectCode)},
    assets: ${JSON.stringify(p.assets)},
    html: ${literal(p.html)},
  },`,
  )
  .join('\n')}
]

/** Match a pasted URL to a bundled package by ARCHON project code. */
export const bundledFor = (url: string): BundledProject | undefined => {
  const trimmed = url.trim().replace(/[?#].*$/, '').replace(/\\/$/, '')
  const code = trimmed.slice(trimmed.lastIndexOf('-') + 1)
  return BUNDLED_PROJECTS.find((p) => p.projectCode === code || p.url === trimmed)
}
`
await writeFile(OUT_TS, source, 'utf8')
console.log(`wrote ${OUT_TS} (${(source.length / 1e6).toFixed(2)} MB) and ${OUT_ASSETS}`)
